#!/bin/bash

echo "STARTING LINUX-DEPS"

if [ -x "$(command -v apt-get)" ]; #debian
then 
  sudo apt-get install -y gcc make autoconf 
  sudo apt-get install -y libcurl4-openssl-dev libffi-dev
  sudo apt-get install -y libbz2-dev zlib1g-dev libncurses5-dev libncursesw5-dev liblzma-dev; 
elif [ -x "$(command -v yum)" ]; # red-hat
then
  sudo yum install -y gcc make autoconf
  sudo yum install -y openssl11-devel
  sudo yum install -y libffi libffi-devel zlib-devel
  sudo yum install -y bzip2-devel bzip2-libs xz-devel xz-libs
elif [ -x "$(command -v pacman)" ]; # arch
then
  sudo pacman -Syu gcc make autoconf2.71
  sudo pacman -Syu openssl libffi
  sudo pacman -Syu libbz2-devel zlib ncurses-devel xz
elif [ -x "$(command -v dnf)" ]; # fedora
then
   sudo dnf install -y gcc make autoconf
   sudo dnf install -y openssl1.1-devel libffi libffi-devel
   sudo dnf install -y bzip2-libs ncurses-devel xz-devel xz-libs
fi


which python3
python3 --version

#curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
#python3 get-pip.py

python3 -m pip install pip --upgrade

which pip3

git submodule init
git submodule update

curl -O https://www.libssh2.org/download/libssh2-1.9.0.tar.gz
tar xzf libssh2-1.9.0.tar.gz
cd libssh2-1.9.0
./configure --prefix=/root
make
make install
cd ..
rm -rf libssh2-1.9.0

curl -O https://curl.se/download/curl-7.73.0.tar.gz
tar xzf curl-7.73.0.tar.gz
cd curl-7.73.0
./configure --with-libssh2 --prefix=/root
make
make install
cd ..
rm -rf curl-7.73.0

ls


cd dysgu/htslib
autoheader
autoconf
./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2
make
make install
cd ../../

echo "LINUX-DEPS DONE"
