#!/bin/bash

echo "STARTING LINUX-DEPS"

ls

yum install -y openssl11-devel
yum install -y libffi libffi-devel zlib-devel
yum install -y bzip2-devel bzip2-libs xz-devel xz-libs

which python
python --version

#curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
#python get-pip.py

python -m pip install pip --upgrade

which pip

pip install numpy

cat requirements.txt
pip install -r requirements.txt

git submodule init
git submodule update

curl -O https://www.libssh2.org/download/libssh2-1.9.0.tar.gz
tar xzf libssh2-1.9.0.tar.gz
cd libssh2-1.9.0
./configure --prefix=/root
make
make install
cd ..
rm -rf libssh2-1.9.0

curl -O https://curl.se/download/curl-7.73.0.tar.gz
tar xzf curl-7.73.0.tar.gz
cd curl-7.73.0
./configure --with-libssh2 --prefix=/root
make
make install
cd ..
rm -rf curl-7.73.0

ls


cd dysgu/htslib
autoheader
autoconf
./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2
make

cd ../../

yum install htslib

echo "LINUX-DEPS DONE"
#pip install -r requirements.txt