#!/bin/bash


BREW_PREFIX="$(brew --prefix)"

export MACOSX_DEPLOYMENT_TARGET=14.0
export CFLAGS="${CFLAGS} -mmacosx-version-min=14.0"
export CPPFLAGS="${CXXFLAGS} -mmacosx-version-min=14.0 -I${BREW_PREFIX}/include "
export LDFLAGS="${LDFLAGS} -mmacosx-version-min=14.0 -L${BREW_PREFIX}/lib"

git clone --depth 1 https://github.com/ebiggers/libdeflate.git
cd libdeflate
CFLAGS+=" -fPIC -O3 " cmake -B build
CFLAGS+=" -fPIC -O3 " cmake --build build
cp build/libdeflate.a ${BREW_PREFIX}/lib
cp libdeflate.h ${BREW_PREFIX}/include
cd ../

cd ./dysgu
wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2
ls -lh
tar -xvf htslib.tar.bz2
mv htslib-1.21 htslib && rm htslib.tar.bz2
cd htslib

./configure \
 --enable-libcurl \
 --enable-s3 \
 --enable-lzma \
 --enable-bz2 \
 --with-libdeflate

sudo make
sudo make install
