#!/bin/bash

git clone --depth 1 https://github.com/ebiggers/libdeflate.git && \
    cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build && \
    cp build/libdeflate.a /usr/local/lib && cp libdeflate.h /usr/local/include && cd ../

cd ./dysgu
wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
ls -lh
tar -xvf htslib.tar.bz2
mv htslib-1.17 htslib && rm htslib.tar.bz2
cd htslib

./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
make

#cd ../../
#pip install -r requirements.txt
