#!/bin/bash
# Install build dependencies. Run from inside dysgu folder

echo "STARTING UBUNTU-DEPS"

apt-get install -y gcc make autoconf wget
apt-get install -y libcurl4-openssl-dev libffi-dev libcurl-dev libssh-dev \
libs3-dev libbz2-dev zlib1g-dev libncurses5-dev libncursesw5-dev liblzma-dev libdeflate-dev 

cd dysgu
wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
tar -xvf htslib.tar.bz2
mv htslib-1.17 htslib && rm htslib.tar.bz2
cd htslib

autoheader
autoconf
./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
make -j8
cd ../../

pip install cython numpy

echo "UBUNTU_DEPS DONE"
